config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'users#index'
  post 'rooms/new'
  get 'users/profile', to: 'users#profile' 
  
  get 'users/profile/edit', to: 'users#edit'
  patch 'users/profile/edit', to: 'users#update'
  
  resources :users 

  resources :rooms do
    resources :reservations
    collection do
      get 'search'
    end
  end

  resources :reservations





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

  mount_uploader :icon, IconUploader
  
  validates :name, presence: true
  validates :email, presence: true
  validates :icon, presence: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name,:email,:password,:icon))
    if @user.save
      flash[:notice]="ユーザーを新規登録しました"
      redirect_to :users
    else
      flash[:notice]="登録に失敗しました"
      render "new"
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(params.require(:user).permit(:icon,:introduction))
      flash[:notice] = "ユーザーの情報を更新しました"
      redirect_to action: :profile
    else
      render 'edit'
    end
  end

  def destroy
  end

  def profile
    @user = current_user
  end

  def image_for
    @user = User.find(params[:id])
    send_data(@user.image)
  end

  def user_params
    params.require(:user).permit(:name, :email, :encrypted_password, :icon) # 変更後
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="account-navi">
  <p class="choice-account"><%= link_to'アカウント',current_user%></p>
  <p class="choice-profile"><%= link_to'プロフィール',users_profile_path%></p>
</div>

<h2>プロフィール情報更新</h2>
<% if flash[:notice]%>
  <p class="notice-ok"><%= flash[:notice]%></p>
<%end%>

<%= form_with model: @user do |f| %>
  <table>
    <tr>
      <th><%= f.label :icon,"アイコン" %></th>
      <td><%= f.file_field :icon %></td>
    </tr>
    <tr>
      <th><%= f.label :introduction,"自己紹介文" %></th>
      <td><%= f.text_area :introduction %></td>
    </tr>
  </table>

  <%= f.submit "編集を完了する" %>
<%end%>

app/views/users/index.html.erb
<% if flash[:notice]%>
  <p class="notice-ok"><%= flash[:notice]%></p>
<%end%>

<div class ="container">
  <div class="top_img">
    <div class="serch_area">
      <h3>Pote Shareでまだ体験したことのない旅をしよう</h3>
      <br>
      <p class="area">エリア</p>
      
      <%= search_form_for @q, url: search_rooms_path do |f| %>
        <%= f.search_field :adress_cont, placeholder:'東京' %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
    
    </div>
  </div>
  <div class="recomend_area">
    <h2>オススメのエリア</h2>
    <div class="grid">
      <div class="grid_child_1">
        <%= link_to '東京',{:controller=>"rooms",:action=>"search",:q=>{:adress_cont=>'東京'}}%><br>
        <%=image_tag 'img_tokyo.jpeg', size: '250x350' %>
      </div>
      <div class="grid_child_2">
        <%= link_to '大阪',{:controller=>"rooms",:action=>"search",:q=>{:adress_cont=>'大阪'}}%><br>
        <%=image_tag 'img_osaka.jpeg', size: '250x350' %>
      </div>
      <div class="grid_child_3">
        <%= link_to '京都',{:controller=>"rooms",:action=>"search",:q=>{:adress_cont=>'京都'}}%><br>
        <%=image_tag 'img_kyoto.jpeg', size: '250x350' %>
      </div>
      <div class="grid_child_4">
        <%= link_to '札幌',{:controller=>"rooms",:action=>"search",:q=>{:adress_cont=>'札幌'}}%><br>
        <%=image_tag 'img_sapporo.jpeg', size: '250x350' %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<% if flash[:notice]%>
  <p class="notice-ok"><%= flash[:notice]%></p>
<%end%>

<div class="account-navi">
  <p class="choice-account"><%= link_to'アカウント',current_user%></p>
  <p class="choice-profile"><%= link_to'プロフィール',users_profile_path%></p>
</div>

<h2>プロフィール画面</h2>

<div class ="profile-container">
  <div class="profile-icon">
    <%= image_tag @user.icon.url, class: "icon"%>
  </div>
  <div class="profile-name">
    <%= @user.name%>
  </div>
  <div class="profile-introduction">
    <%= @user.introduction%>
  </div>
</div>

<button>
  <%=link_to "編集する", "profile/edit"%>
</button>

app/views/users/show.html.erb
<div class="account-navi">
  <p class="choice-account"><%= link_to'アカウント', current_user%></p>
  <p class="choice-profile"><%= link_to'プロフィール', users_profile_path%></p>
</div>

<h2>アカウント情報</h2>
<div class="under-bar">
  <p>メールアドレス</p>
  <%= @user.email%>
</div>

<div>
  <p>パスワード</p>
  <p>＊＊＊＊＊＊＊＊</p>
</div>

<button>
  <%= link_to'編集する', edit_user_registration_path%>
</button>