config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'users#index'
  post 'rooms/new'
  get 'users/profile', to: 'users#profile' 
  
  get 'users/profile/edit', to: 'users#edit'
  patch 'users/profile/edit', to: 'users#update'
  
  resources :users 

  resources :rooms do
    resources :reservations
    collection do
      get 'search'
    end
  end

  resources :reservations





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :reservations, dependent: :destroy

  belongs_to :user
  
  mount_uploader :avatar, AvatarUploader
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :adress, presence: true
  validates :avatar, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q
  before_action :search
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    
    @room = Room.new(params.require(:room).permit(:name,:introduction,:price,:adress,:avatar,:user_id))
    
    if @room.save!
      flash[:notice]="ルームを新規登録しました"
      redirect_to :rooms
    else
      
      flash[:notice]="登録に失敗しました"
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "削除しました"
    redirect_to :rooms
  end

  def image_for
    @room = Room.find(params[:id])
    send_data(@room.image)
  end

  def set_q
    @q = Room.ransack(params[:q])
  end
  
  def search
    @results = @q.result
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<h3>登録済みルーム一覧</h3>

<% if flash[:notice]%>
  <p class="notice-ok"><%= flash[:notice]%></p>
<%end%>

<table>
  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>登録日</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= image_tag room.avatar.url %></td>
        <td><%= room.name%></td>
        <td><%= room.introduction %></td>
        <td><%= room.price %></td>
        <td><%= room.created_at.strftime('%Y年%m月%d日') %></td>
        <td><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/new.html.erb
<h3 class=room-new-title>ルーム登録</h3>

<% if flash[:notice]%>
  <p class="notice-ok"><%= flash[:notice]%></p>
<%end%>

<%= form_with model:@room do |f| %>
  <table cellpadding="30" border-bottom="1">

    <tr class="table-title">
      <th><%= f.label :name ,"ルーム名" %><span class="attention">必須</span></th>
      <td><%= f.text_field :name, :placeholder => "ルーム名を入力" %></td>
    </tr>

    <tr class="table-title">
      <th><%= f.label :introduction ,"ルーム紹介" %><span class="attention">必須</span></th>
      <td><%= f.text_area :introduction , :placeholder => "ルーム説明を入力"%></td>
    </tr>

    <tr class="table-title">
      <th><%= f.label :price ,"料金" %><span class="attention">必須</span></th>
      <td><%= f.text_field :price , :placeholder => "1日あたりの料金を入力"%></td>
    </tr>

    <tr class="table-title">
      <th><%= f.label :adress ,"住所" %><span class="attention">必須</span></th>
      <td><%= f.text_field :adress , :placeholder => "住所を入力"%></td>
    </tr>

    <tr class="table-title">
      <th><%= f.label :avatar ,"イメージ画像"%><span class="attention">必須</span></th>
      <td><%= f.file_field :avatar %></td>
    </tr>
  </table>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div>
    <ul>
      <li><%= f.submit "登録"%></li>
      <li><%= link_to "TOPに戻る", :users %></li>
    </ul>
  </div>
<%end%>

app/views/rooms/search.html.erb
<h1>検索結果</h1>
<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>画像</th>
      <th>住所</th>
      <th>価格</th>
      <th>紹介文</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |room| %>
      <tr>
        <td><%=link_to room.name, new_reservation_path(room.id) %></td>
        <td><%= image_tag room.avatar.url%></td>
        <td><%= room.adress %></td>
        <td><%= room.price %></td>
        <td><%= room.introduction %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Top', users_path %>